"""add relationships

Revision ID: 3239af58741b
Revises: 8992ebacf6c1
Create Date: 2026-05-07 09:08:45.063388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3239af58741b'
down_revision: Union[str, Sequence[str], None] = '8992ebacf6c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'attempts', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'attempts', 'exams', ['exam_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'attempts', type_='foreignkey')
    op.drop_constraint(None, 'attempts', type_='foreignkey')
    # ### end Alembic commands ###
