"""add timestamps

Revision ID: 54227e1ace0a
Revises: 9352dd941767
Create Date: 2026-05-07 20:19:13.788740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54227e1ace0a'
down_revision: Union[str, Sequence[str], None] = '9352dd941767'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('attempts', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('attempts', sa.Column('submitted_at', sa.DateTime(), nullable=True))
    op.add_column('exams', sa.Column('created_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exams', 'created_at')
    op.drop_column('attempts', 'submitted_at')
    op.drop_column('attempts', 'created_at')
    op.drop_column('answers', 'created_at')
    # ### end Alembic commands ###
