"""add nullable constraints

Revision ID: 9352dd941767
Revises: fcb722be0256
Create Date: 2026-05-07 10:15:10.794701

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9352dd941767'
down_revision: Union[str, Sequence[str], None] = 'fcb722be0256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attempts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('attempts', 'exam_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('attempts', 'exam_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('attempts', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
